### ISSUE TITLE
404

### ISSUE THREAD

**Issue by tpoonach** [captain-zsa/flogmall__white#1]
the link you give is 404
See official page https://flogmall.com/white/

**Comment by captain-zsa** [comment]
Thank you. Indeed, we changed the url of this page. Now this: http://flogmall.com/wp/?lang=en

**Comment by tpoonach** [comment]
Now how about some coins for a bug bounty
0xeC5D1FDce9Fb1651a20fAc9fCCA72bD5EE8F3EBd

Sent with [ProtonMail](https://protonmail.com) Secure Email.

-------- Original Message --------

**Comment by captain-zsa** [comment]
I did not understand. Do you want to be rewarded for reminding me of the link? Or do you want to help improve our bounty campaign?

**Comment by tpoonach** [comment]
I would like to see a rewards program like utopian.io where developers can earn coins from your project by helping reporting bugs and writing code on the open source side of the offer.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

-------- Original Message --------

**Comment by captain-zsa** [comment]
https://flogmall.com/bounty or
https://bitcointalk.org/index.php?topic=2790987.0

**Comment by tpoonach** [comment]
Yes, I have seen these, I am talking about coding tasks, testing, QC, design.
